---
- name: Play with vars of the Play
  hosts: localhost
  vars:
    ip: '192.16.100.1'
  tags:
    var_play
  tasks:
    - name: Display variable task
      debug:
        msg: "The IP from the local vars of the Play {{ip}}"

- name: Play with vars_files of the Play               
  hosts: localhost
  gather_facts: false
  tags:
    file_var_play
  vars_files:
    - var_file.yaml
  tasks:
    - name: Display file variable task
      debug:
        msg: "The IP from the vars_files mentioned in the Play : {{ip}}"

- name: Play with templates
  hosts: localhost
  vars:
    loopback_ip: 127.0.0.10
    subnet_mask: 255.255.255.0
  tags:
    template_play
  tasks:
    - name: Template Task One
      template:
        src: 'loopback_template.j2'
        dest: 'template_outputs/loopback10.conf'
